name: diabetes prediction deploy

on:
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "newMain" ]
    #types: [closed]

jobs:
  build:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Maven
      working-directory: diabetes-prediction
      run: mvn clean install -U -DprofileIdEnabled=true -DskipTests -Dfile=diabetes-prediction.jar -DgroupId=com.zbeu -DartifactId=diabetes-prediction -Dversion=0.0.1 -Dpackaging=jar -DgeneratePom=true
      
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
          image: hakanyigit/diabetes-prediction-backend
          tags: latest
          registry: docker.io
          dockerfile: diabetes-prediction/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
